name: Build Android APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: |
          cd sms-gateway
          # Halkii aan ka isticmaali lahayn 'npm ci', waxaan isticmaalaynaa 'install'
          npm install --legacy-peer-deps

      - name: 🚀 Build APK (Force Build)
        run: |
          cd sms-gateway
          # Waxaan amraynaa inuu iska indho-tiro 'npm ci' oo uu koodhka hadda jira dhismahiisa bilaabo
          eas build --platform android --profile development --local --non-interactive --clear-cache